### ISSUE TITLE
A problem about "regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11})."

### ISSUE THREAD

**Issue by LiuXinqi12** [arielai/youtube_3d_hands#8]
Hi, when I run your program "python download_images.py --vid VIDEO_ID", there is a problem  "regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11})."occured. It seems to be related to pytube, but after I modified it according to the suggestions on github(https://github.com/nficano/pytube/issues/312#issuecomment-447660395), it still doesn't  work, so I cannot get the dataset. In addition, program "python download_images.py --set train" seem can work. The pytube version I use is "9.6.4", can you give me some help? Thank you very much!

**Comment by chaitanya-kaul** [comment]
You might have the wrong version of pytube. Uninstall it using, 
            pip uninstall pytube 
and then install using this,  
            pip install git+https://github.com/nficano/pytube.git
It should fix the problem.

**Comment by booker-max** [comment]
@chaitanya-kaul @LiuXinqi12 Hello, I tried according to your method, installed pytube-10.8.5, but when I run the code, I still get an error.
![image](https://user-images.githubusercontent.com/74257220/123366605-11d18600-d5ab-11eb-93ba-240e5a979dcf.png)

**Comment by booker-max** [comment]
> Hi, when I run your program "python download_images.py --vid VIDEO_ID", there is a problem "regex_search: could not find match for (?:v=|/)([0-9A-Za-z_-]{11})."occured. It seems to be related to pytube, but after I modified it according to the suggestions on github([pytube/pytube#312 (comment)](https://github.com/pytube/pytube/issues/312#issuecomment-447660395)), it still doesn't work, so I cannot get the dataset. In addition, program "python download_images.py --set train" seem can work. The pytube version I use is "9.6.4", can you give me some help? Thank you very much!

Hello, I am experiencing the same question as you, do you solve it?

**Comment by hazalx** [comment]
> > Hi, when I run your program "python download_images.py --vid VIDEO_ID", there is a problem "regex_search: could not find match for (?:v=|/)([0-9A-Za-z_-]{11})."occured. It seems to be related to pytube, but after I modified it according to the suggestions on github([pytube/pytube#312 (comment)](https://github.com/pytube/pytube/issues/312#issuecomment-447660395)), it still doesn't work, so I cannot get the dataset. In addition, program "python download_images.py --set train" seem can work. The pytube version I use is "9.6.4", can you give me some help? Thank you very much!
> 
> Hello, I am experiencing the same question as you, do you solve it?

Hi, did u solve this problem? I also have  the same issue :(

**Comment by jaychovatiya4995** [comment]
> You might have the wrong version of pytube. Uninstall it using, pip uninstall pytube and then install using this, pip install git+https://github.com/nficano/pytube.git It should fix the problem.

Hi, I have a latest version of pytube 11.0.1, but I have fetch the same error :(  

Any One solve it..?

**Comment by xsraut** [comment]
> pip uninstall pytube
> and then install using this,
> pip install git+https://github.com/nficano/pytube.git

Worked for me...Thanks

**Comment by Midhunmiyu** [comment]
Still its not working

**Comment by Swastikbanarjee** [comment]
I did all listed above still getting error
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Sushmita\PycharmProjects\pythonProject1\main.py", line 30, in Download
    getVideo=YouTube(youTube_link)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sushmita\PycharmProjects\pythonProject1\venv\Lib\site-packages\pytube\__main__.py", line 71, in __init__
    self.video_id = extract.video_id(url)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sushmita\PycharmProjects\pythonProject1\venv\Lib\site-packages\pytube\extract.py", line 133, in video_id
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sushmita\PycharmProjects\pythonProject1\venv\Lib\site-packages\pytube\helpers.py", line 129, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*

version 15.0.0
